// Refreshes the vendored assets/ from the make-it-in-china asset library: only the GLBs
// src/layout.json uses, plus an index.json listing only those. Run after the library is rebuilt
// (tools/blender/build_all.py) or layout.json starts using a new asset:
//
//   npm run assets:sync -w @silver-tongue/world3d      (WORLD3D_ASSETS=... to point elsewhere)
//
// The library defaults to ../assets next to the repo checkout (the make-it-in-china layout).
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { copyUsed } from "./used-assets.mjs";

const here = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = process.env.WORLD3D_ASSETS ?? join(here, "..", "..", "..", "assets");
const out = join(here, "assets");
if (!existsSync(join(src, "index.json"))) throw new Error(`no asset library at ${src} (set WORLD3D_ASSETS)`);

const n = copyUsed(src, out, join(here, "src", "layout.json"));
writeFileSync(
  join(out, "README.md"),
  `# Vendored assets\n\nGenerated by make-it-in-china tools/blender/build_all.py; do not hand-edit. Only the GLBs\n\`src/layout.json\` uses, plus an \`index.json\` listing only those.\n\nRegenerate with \`npm run assets:sync -w @silver-tongue/world3d\` (copies from \`WORLD3D_ASSETS\`,\ndefault \`../assets\` next to the repo checkout).\n`,
);
const size = (d) => readdirSync(d).reduce((s, f) => s + (statSync(join(d, f)).isDirectory() ? size(join(d, f)) : statSync(join(d, f)).size), 0);
console.log(`synced packages/world3d/assets: ${n} GLBs from ${src}, ${(size(out) / 1048576).toFixed(1)} MB`);
